name: inflation_by_income_percentile
channels:
  - defaults
dependencies:
  - beautifulsoup4>=4.10.0
  - black>=23.3.0
  - cryptography>=3.4.8
  - curl>=7.78.0
  - flask>=1.1.2
  - jinja2>=2.11.3
  - jupyter>=1.0.0
  - numba>=0.54.1
  - numpy>=1.20.3
  - openssl>=1.1.1w
  - pandas>=1.3.4
  - pyarrow>=4.0.1
  - python>=3.7.11
  - pytz>=2021.3
  - regex>=2021.8.3
  - scikit-learn>=1.0.1
  - seaborn>=0.11.2
  - sqlite>=3.36.0
  - urllib3>=1.26.7
  - xlsxwriter>=3.0.2
  - yaml>=0.2.5
  - openpyxl>=3.0.9
  - pip:
    - duckdb>=1.3.0
    - optuna>=2.10.0
    - pip>=22.3
    - plotly>=5.6.0
    - pygithub>=1.55
    - pyperclip>=1.8.2
    - selenium>=4.1.3
    - setuptools>=62.0.0
