name: inflation_by_income_percentile
channels:
  - conda-forge        # first so you always get the -forge builds
  - defaults
dependencies:
  # core runtime
  - python=3.12
  - pip

  # data‑science stack (all available on conda-forge)
  - pandas>=1.3
  - numpy>=1.20
  - duckdb>=1.3
  - pyarrow>=4.0
  - scikit-learn>=1.0
  - seaborn>=0.11
  - plotly>=5.6
  - optuna>=2.10

  # web / scraping / utils
  - beautifulsoup4>=4.10
  - cryptography>=3.4
  - curl>=7.78
  - flask>=1.1
  - pygithub>=1.55
  - selenium>=4.1
  - pyperclip>=1.8
  - urllib3>=1.26

  # Jupyter & tooling
  - jupyterlab
  - notebook           # comes in automatically but keep it explicit
  - ipykernel
  - debugpy
  - black>=23.3

  # **only** packages unavailable on Conda go here
  - pip:
      - regex>=2021.8.3        # ← example of PyPI‑only package
      - debugsnap
